/* eslint-disable */

// @ts-nocheck

// This file was automatically generated by @caffeinelabs/bindgen@0.1.0.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import type { ActorMethod } from '@icp-sdk/core/agent';
import type { IDL } from '@icp-sdk/core/candid';
import type { Principal } from '@icp-sdk/core/principal';

export type ApplicationId = bigint;
export type ApplicationStatus = { 'offer' : null } |
  { 'interview' : null } |
  { 'applied' : null } |
  { 'rejected' : null } |
  { 'shortlisted' : null };
export interface EmployeeProfile {
  'userId' : UserId,
  'resumeFileId' : [] | [ExternalBlob],
  'experience' : Array<ExperienceEntry>,
  'phone' : string,
  'skills' : Array<string>,
  'location' : string,
  'professionalSummary' : string,
}
export interface EmployerProfile {
  'status' : EmployerStatus,
  'userId' : UserId,
  'description' : string,
  'companyEmail' : string,
  'companyName' : string,
  'companySize' : string,
  'industry' : string,
}
export type EmployerStatus = { 'pending' : null } |
  { 'approved' : null } |
  { 'suspended' : null };
export interface ExperienceEntry {
  'title' : string,
  'endDate' : [] | [string],
  'description' : string,
  'company' : string,
  'startDate' : string,
}
export type ExternalBlob = Uint8Array;
export interface JobApplication {
  'status' : ApplicationStatus,
  'appliedAt' : Timestamp,
  'applicationId' : ApplicationId,
  'jobId' : JobId,
  'updatedAt' : Timestamp,
  'employeeId' : UserId,
  'notes' : [] | [string],
}
export type JobId = bigint;
export interface JobListing {
  'applicationDeadline' : Timestamp,
  'status' : JobStatus,
  'title' : string,
  'jobType' : JobType,
  'createdAt' : Timestamp,
  'experienceRequired' : bigint,
  'jobId' : JobId,
  'skillsRequired' : Array<string>,
  'description' : string,
  'updatedAt' : Timestamp,
  'employerId' : UserId,
  'salaryMax' : bigint,
  'salaryMin' : bigint,
  'location' : string,
}
export interface JobSearchFilter {
  'jobType' : [] | [JobType],
  'salaryMax' : [] | [bigint],
  'salaryMin' : [] | [bigint],
  'keyword' : [] | [string],
  'location' : [] | [string],
}
export type JobStatus = { 'closed' : null } |
  { 'active' : null } |
  { 'draft' : null };
export type JobType = { 'contract' : null } |
  { 'partTime' : null } |
  { 'fullTime' : null };
export interface PlatformStats {
  'totalEmployees' : bigint,
  'totalEmployers' : bigint,
  'totalJobs' : bigint,
  'totalUsers' : bigint,
  'activeJobs' : bigint,
  'totalApplications' : bigint,
}
export type Timestamp = bigint;
export interface User {
  'status' : UserStatus,
  'principal' : UserId,
  'name' : string,
  'createdAt' : Timestamp,
  'role' : UserRole,
  'email' : string,
}
export type UserId = Principal;
export type UserRole = { 'admin' : null } |
  { 'employee' : null } |
  { 'employer' : null };
export type UserRole__1 = { 'admin' : null } |
  { 'user' : null } |
  { 'guest' : null };
export type UserStatus = { 'active' : null } |
  { 'inactive' : null };
export interface _ImmutableObjectStorageCreateCertificateResult {
  'method' : string,
  'blob_hash' : string,
}
export interface _ImmutableObjectStorageRefillInformation {
  'proposed_top_up_amount' : [] | [bigint],
}
export interface _ImmutableObjectStorageRefillResult {
  'success' : [] | [boolean],
  'topped_up_amount' : [] | [bigint],
}
export interface _SERVICE {
  '_immutableObjectStorageBlobsAreLive' : ActorMethod<
    [Array<Uint8Array>],
    Array<boolean>
  >,
  '_immutableObjectStorageBlobsToDelete' : ActorMethod<[], Array<Uint8Array>>,
  '_immutableObjectStorageConfirmBlobDeletion' : ActorMethod<
    [Array<Uint8Array>],
    undefined
  >,
  '_immutableObjectStorageCreateCertificate' : ActorMethod<
    [string],
    _ImmutableObjectStorageCreateCertificateResult
  >,
  '_immutableObjectStorageRefillCashier' : ActorMethod<
    [[] | [_ImmutableObjectStorageRefillInformation]],
    _ImmutableObjectStorageRefillResult
  >,
  '_immutableObjectStorageUpdateGatewayPrincipals' : ActorMethod<[], undefined>,
  '_initializeAccessControl' : ActorMethod<[], undefined>,
  'applyToJob' : ActorMethod<[JobId], ApplicationId>,
  'approveEmployer' : ActorMethod<[UserId], undefined>,
  'approveJob' : ActorMethod<[JobId], undefined>,
  'assignCallerUserRole' : ActorMethod<[Principal, UserRole__1], undefined>,
  'deactivateUser' : ActorMethod<[UserId], undefined>,
  'getCallerUserRole' : ActorMethod<[], UserRole__1>,
  'getEmployeeProfile' : ActorMethod<[UserId], [] | [EmployeeProfile]>,
  'getEmployerProfile' : ActorMethod<[UserId], [] | [EmployerProfile]>,
  'getJobApplications' : ActorMethod<[JobId], Array<JobApplication>>,
  'getJobDetails' : ActorMethod<[JobId], [] | [JobListing]>,
  'getMyApplications' : ActorMethod<[], Array<JobApplication>>,
  'getMyEmployerJobs' : ActorMethod<[], Array<JobListing>>,
  'getMyProfile' : ActorMethod<[], [] | [User]>,
  'getPlatformStats' : ActorMethod<[], PlatformStats>,
  'getSavedJobs' : ActorMethod<[], Array<JobListing>>,
  'getUserList' : ActorMethod<[], Array<User>>,
  'isCallerAdmin' : ActorMethod<[], boolean>,
  'postJob' : ActorMethod<
    [
      string,
      string,
      string,
      bigint,
      bigint,
      bigint,
      JobType,
      Array<string>,
      Timestamp,
    ],
    JobId
  >,
  'reactivateUser' : ActorMethod<[UserId], undefined>,
  'registerUser' : ActorMethod<[UserRole, string, string], undefined>,
  'rejectJob' : ActorMethod<[JobId], undefined>,
  'saveJob' : ActorMethod<[JobId], undefined>,
  'searchJobs' : ActorMethod<[JobSearchFilter], Array<JobListing>>,
  'suspendEmployer' : ActorMethod<[UserId], undefined>,
  'unsaveJob' : ActorMethod<[JobId], undefined>,
  'updateApplicationStatus' : ActorMethod<
    [ApplicationId, ApplicationStatus, [] | [string]],
    undefined
  >,
  'updateEmployeeProfile' : ActorMethod<
    [
      string,
      string,
      Array<string>,
      string,
      Array<ExperienceEntry>,
      [] | [ExternalBlob],
    ],
    undefined
  >,
  'updateEmployerProfile' : ActorMethod<
    [string, string, string, string, string],
    undefined
  >,
  'updateJob' : ActorMethod<
    [
      JobId,
      string,
      string,
      string,
      bigint,
      bigint,
      bigint,
      JobType,
      Array<string>,
      JobStatus,
      Timestamp,
    ],
    undefined
  >,
}
export declare const idlService: IDL.ServiceClass;
export declare const idlInitArgs: IDL.Type[];
export declare const idlFactory: IDL.InterfaceFactory;
export declare const init: (args: { IDL: typeof IDL }) => IDL.Type[];