/* eslint-disable */

// @ts-nocheck

// This file was automatically generated by @caffeinelabs/bindgen@0.1.0.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { IDL } from '@icp-sdk/core/candid';

export const _ImmutableObjectStorageCreateCertificateResult = IDL.Record({
  'method' : IDL.Text,
  'blob_hash' : IDL.Text,
});
export const _ImmutableObjectStorageRefillInformation = IDL.Record({
  'proposed_top_up_amount' : IDL.Opt(IDL.Nat),
});
export const _ImmutableObjectStorageRefillResult = IDL.Record({
  'success' : IDL.Opt(IDL.Bool),
  'topped_up_amount' : IDL.Opt(IDL.Nat),
});
export const JobId = IDL.Nat;
export const ApplicationId = IDL.Nat;
export const UserId = IDL.Principal;
export const UserRole__1 = IDL.Variant({
  'admin' : IDL.Null,
  'user' : IDL.Null,
  'guest' : IDL.Null,
});
export const ExternalBlob = IDL.Vec(IDL.Nat8);
export const ExperienceEntry = IDL.Record({
  'title' : IDL.Text,
  'endDate' : IDL.Opt(IDL.Text),
  'description' : IDL.Text,
  'company' : IDL.Text,
  'startDate' : IDL.Text,
});
export const EmployeeProfile = IDL.Record({
  'userId' : UserId,
  'resumeFileId' : IDL.Opt(ExternalBlob),
  'experience' : IDL.Vec(ExperienceEntry),
  'phone' : IDL.Text,
  'skills' : IDL.Vec(IDL.Text),
  'location' : IDL.Text,
  'professionalSummary' : IDL.Text,
});
export const EmployerStatus = IDL.Variant({
  'pending' : IDL.Null,
  'approved' : IDL.Null,
  'suspended' : IDL.Null,
});
export const EmployerProfile = IDL.Record({
  'status' : EmployerStatus,
  'userId' : UserId,
  'description' : IDL.Text,
  'companyEmail' : IDL.Text,
  'companyName' : IDL.Text,
  'companySize' : IDL.Text,
  'industry' : IDL.Text,
});
export const ApplicationStatus = IDL.Variant({
  'offer' : IDL.Null,
  'interview' : IDL.Null,
  'applied' : IDL.Null,
  'rejected' : IDL.Null,
  'shortlisted' : IDL.Null,
});
export const Timestamp = IDL.Int;
export const JobApplication = IDL.Record({
  'status' : ApplicationStatus,
  'appliedAt' : Timestamp,
  'applicationId' : ApplicationId,
  'jobId' : JobId,
  'updatedAt' : Timestamp,
  'employeeId' : UserId,
  'notes' : IDL.Opt(IDL.Text),
});
export const JobStatus = IDL.Variant({
  'closed' : IDL.Null,
  'active' : IDL.Null,
  'draft' : IDL.Null,
});
export const JobType = IDL.Variant({
  'contract' : IDL.Null,
  'partTime' : IDL.Null,
  'fullTime' : IDL.Null,
});
export const JobListing = IDL.Record({
  'applicationDeadline' : Timestamp,
  'status' : JobStatus,
  'title' : IDL.Text,
  'jobType' : JobType,
  'createdAt' : Timestamp,
  'experienceRequired' : IDL.Nat,
  'jobId' : JobId,
  'skillsRequired' : IDL.Vec(IDL.Text),
  'description' : IDL.Text,
  'updatedAt' : Timestamp,
  'employerId' : UserId,
  'salaryMax' : IDL.Nat,
  'salaryMin' : IDL.Nat,
  'location' : IDL.Text,
});
export const UserStatus = IDL.Variant({
  'active' : IDL.Null,
  'inactive' : IDL.Null,
});
export const UserRole = IDL.Variant({
  'admin' : IDL.Null,
  'employee' : IDL.Null,
  'employer' : IDL.Null,
});
export const User = IDL.Record({
  'status' : UserStatus,
  'principal' : UserId,
  'name' : IDL.Text,
  'createdAt' : Timestamp,
  'role' : UserRole,
  'email' : IDL.Text,
});
export const PlatformStats = IDL.Record({
  'totalEmployees' : IDL.Nat,
  'totalEmployers' : IDL.Nat,
  'totalJobs' : IDL.Nat,
  'totalUsers' : IDL.Nat,
  'activeJobs' : IDL.Nat,
  'totalApplications' : IDL.Nat,
});
export const JobSearchFilter = IDL.Record({
  'jobType' : IDL.Opt(JobType),
  'salaryMax' : IDL.Opt(IDL.Nat),
  'salaryMin' : IDL.Opt(IDL.Nat),
  'keyword' : IDL.Opt(IDL.Text),
  'location' : IDL.Opt(IDL.Text),
});

export const idlService = IDL.Service({
  '_immutableObjectStorageBlobsAreLive' : IDL.Func(
      [IDL.Vec(IDL.Vec(IDL.Nat8))],
      [IDL.Vec(IDL.Bool)],
      ['query'],
    ),
  '_immutableObjectStorageBlobsToDelete' : IDL.Func(
      [],
      [IDL.Vec(IDL.Vec(IDL.Nat8))],
      ['query'],
    ),
  '_immutableObjectStorageConfirmBlobDeletion' : IDL.Func(
      [IDL.Vec(IDL.Vec(IDL.Nat8))],
      [],
      [],
    ),
  '_immutableObjectStorageCreateCertificate' : IDL.Func(
      [IDL.Text],
      [_ImmutableObjectStorageCreateCertificateResult],
      [],
    ),
  '_immutableObjectStorageRefillCashier' : IDL.Func(
      [IDL.Opt(_ImmutableObjectStorageRefillInformation)],
      [_ImmutableObjectStorageRefillResult],
      [],
    ),
  '_immutableObjectStorageUpdateGatewayPrincipals' : IDL.Func([], [], []),
  '_initializeAccessControl' : IDL.Func([], [], []),
  'applyToJob' : IDL.Func([JobId], [ApplicationId], []),
  'approveEmployer' : IDL.Func([UserId], [], []),
  'approveJob' : IDL.Func([JobId], [], []),
  'assignCallerUserRole' : IDL.Func([IDL.Principal, UserRole__1], [], []),
  'deactivateUser' : IDL.Func([UserId], [], []),
  'getCallerUserRole' : IDL.Func([], [UserRole__1], ['query']),
  'getEmployeeProfile' : IDL.Func(
      [UserId],
      [IDL.Opt(EmployeeProfile)],
      ['query'],
    ),
  'getEmployerProfile' : IDL.Func(
      [UserId],
      [IDL.Opt(EmployerProfile)],
      ['query'],
    ),
  'getJobApplications' : IDL.Func(
      [JobId],
      [IDL.Vec(JobApplication)],
      ['query'],
    ),
  'getJobDetails' : IDL.Func([JobId], [IDL.Opt(JobListing)], ['query']),
  'getMyApplications' : IDL.Func([], [IDL.Vec(JobApplication)], ['query']),
  'getMyEmployerJobs' : IDL.Func([], [IDL.Vec(JobListing)], ['query']),
  'getMyProfile' : IDL.Func([], [IDL.Opt(User)], ['query']),
  'getPlatformStats' : IDL.Func([], [PlatformStats], ['query']),
  'getSavedJobs' : IDL.Func([], [IDL.Vec(JobListing)], ['query']),
  'getUserList' : IDL.Func([], [IDL.Vec(User)], ['query']),
  'isCallerAdmin' : IDL.Func([], [IDL.Bool], ['query']),
  'postJob' : IDL.Func(
      [
        IDL.Text,
        IDL.Text,
        IDL.Text,
        IDL.Nat,
        IDL.Nat,
        IDL.Nat,
        JobType,
        IDL.Vec(IDL.Text),
        Timestamp,
      ],
      [JobId],
      [],
    ),
  'reactivateUser' : IDL.Func([UserId], [], []),
  'registerUser' : IDL.Func([UserRole, IDL.Text, IDL.Text], [], []),
  'rejectJob' : IDL.Func([JobId], [], []),
  'saveJob' : IDL.Func([JobId], [], []),
  'searchJobs' : IDL.Func([JobSearchFilter], [IDL.Vec(JobListing)], ['query']),
  'suspendEmployer' : IDL.Func([UserId], [], []),
  'unsaveJob' : IDL.Func([JobId], [], []),
  'updateApplicationStatus' : IDL.Func(
      [ApplicationId, ApplicationStatus, IDL.Opt(IDL.Text)],
      [],
      [],
    ),
  'updateEmployeeProfile' : IDL.Func(
      [
        IDL.Text,
        IDL.Text,
        IDL.Vec(IDL.Text),
        IDL.Text,
        IDL.Vec(ExperienceEntry),
        IDL.Opt(ExternalBlob),
      ],
      [],
      [],
    ),
  'updateEmployerProfile' : IDL.Func(
      [IDL.Text, IDL.Text, IDL.Text, IDL.Text, IDL.Text],
      [],
      [],
    ),
  'updateJob' : IDL.Func(
      [
        JobId,
        IDL.Text,
        IDL.Text,
        IDL.Text,
        IDL.Nat,
        IDL.Nat,
        IDL.Nat,
        JobType,
        IDL.Vec(IDL.Text),
        JobStatus,
        Timestamp,
      ],
      [],
      [],
    ),
});

export const idlInitArgs = [];

export const idlFactory = ({ IDL }) => {
  const _ImmutableObjectStorageCreateCertificateResult = IDL.Record({
    'method' : IDL.Text,
    'blob_hash' : IDL.Text,
  });
  const _ImmutableObjectStorageRefillInformation = IDL.Record({
    'proposed_top_up_amount' : IDL.Opt(IDL.Nat),
  });
  const _ImmutableObjectStorageRefillResult = IDL.Record({
    'success' : IDL.Opt(IDL.Bool),
    'topped_up_amount' : IDL.Opt(IDL.Nat),
  });
  const JobId = IDL.Nat;
  const ApplicationId = IDL.Nat;
  const UserId = IDL.Principal;
  const UserRole__1 = IDL.Variant({
    'admin' : IDL.Null,
    'user' : IDL.Null,
    'guest' : IDL.Null,
  });
  const ExternalBlob = IDL.Vec(IDL.Nat8);
  const ExperienceEntry = IDL.Record({
    'title' : IDL.Text,
    'endDate' : IDL.Opt(IDL.Text),
    'description' : IDL.Text,
    'company' : IDL.Text,
    'startDate' : IDL.Text,
  });
  const EmployeeProfile = IDL.Record({
    'userId' : UserId,
    'resumeFileId' : IDL.Opt(ExternalBlob),
    'experience' : IDL.Vec(ExperienceEntry),
    'phone' : IDL.Text,
    'skills' : IDL.Vec(IDL.Text),
    'location' : IDL.Text,
    'professionalSummary' : IDL.Text,
  });
  const EmployerStatus = IDL.Variant({
    'pending' : IDL.Null,
    'approved' : IDL.Null,
    'suspended' : IDL.Null,
  });
  const EmployerProfile = IDL.Record({
    'status' : EmployerStatus,
    'userId' : UserId,
    'description' : IDL.Text,
    'companyEmail' : IDL.Text,
    'companyName' : IDL.Text,
    'companySize' : IDL.Text,
    'industry' : IDL.Text,
  });
  const ApplicationStatus = IDL.Variant({
    'offer' : IDL.Null,
    'interview' : IDL.Null,
    'applied' : IDL.Null,
    'rejected' : IDL.Null,
    'shortlisted' : IDL.Null,
  });
  const Timestamp = IDL.Int;
  const JobApplication = IDL.Record({
    'status' : ApplicationStatus,
    'appliedAt' : Timestamp,
    'applicationId' : ApplicationId,
    'jobId' : JobId,
    'updatedAt' : Timestamp,
    'employeeId' : UserId,
    'notes' : IDL.Opt(IDL.Text),
  });
  const JobStatus = IDL.Variant({
    'closed' : IDL.Null,
    'active' : IDL.Null,
    'draft' : IDL.Null,
  });
  const JobType = IDL.Variant({
    'contract' : IDL.Null,
    'partTime' : IDL.Null,
    'fullTime' : IDL.Null,
  });
  const JobListing = IDL.Record({
    'applicationDeadline' : Timestamp,
    'status' : JobStatus,
    'title' : IDL.Text,
    'jobType' : JobType,
    'createdAt' : Timestamp,
    'experienceRequired' : IDL.Nat,
    'jobId' : JobId,
    'skillsRequired' : IDL.Vec(IDL.Text),
    'description' : IDL.Text,
    'updatedAt' : Timestamp,
    'employerId' : UserId,
    'salaryMax' : IDL.Nat,
    'salaryMin' : IDL.Nat,
    'location' : IDL.Text,
  });
  const UserStatus = IDL.Variant({
    'active' : IDL.Null,
    'inactive' : IDL.Null,
  });
  const UserRole = IDL.Variant({
    'admin' : IDL.Null,
    'employee' : IDL.Null,
    'employer' : IDL.Null,
  });
  const User = IDL.Record({
    'status' : UserStatus,
    'principal' : UserId,
    'name' : IDL.Text,
    'createdAt' : Timestamp,
    'role' : UserRole,
    'email' : IDL.Text,
  });
  const PlatformStats = IDL.Record({
    'totalEmployees' : IDL.Nat,
    'totalEmployers' : IDL.Nat,
    'totalJobs' : IDL.Nat,
    'totalUsers' : IDL.Nat,
    'activeJobs' : IDL.Nat,
    'totalApplications' : IDL.Nat,
  });
  const JobSearchFilter = IDL.Record({
    'jobType' : IDL.Opt(JobType),
    'salaryMax' : IDL.Opt(IDL.Nat),
    'salaryMin' : IDL.Opt(IDL.Nat),
    'keyword' : IDL.Opt(IDL.Text),
    'location' : IDL.Opt(IDL.Text),
  });
  
  return IDL.Service({
    '_immutableObjectStorageBlobsAreLive' : IDL.Func(
        [IDL.Vec(IDL.Vec(IDL.Nat8))],
        [IDL.Vec(IDL.Bool)],
        ['query'],
      ),
    '_immutableObjectStorageBlobsToDelete' : IDL.Func(
        [],
        [IDL.Vec(IDL.Vec(IDL.Nat8))],
        ['query'],
      ),
    '_immutableObjectStorageConfirmBlobDeletion' : IDL.Func(
        [IDL.Vec(IDL.Vec(IDL.Nat8))],
        [],
        [],
      ),
    '_immutableObjectStorageCreateCertificate' : IDL.Func(
        [IDL.Text],
        [_ImmutableObjectStorageCreateCertificateResult],
        [],
      ),
    '_immutableObjectStorageRefillCashier' : IDL.Func(
        [IDL.Opt(_ImmutableObjectStorageRefillInformation)],
        [_ImmutableObjectStorageRefillResult],
        [],
      ),
    '_immutableObjectStorageUpdateGatewayPrincipals' : IDL.Func([], [], []),
    '_initializeAccessControl' : IDL.Func([], [], []),
    'applyToJob' : IDL.Func([JobId], [ApplicationId], []),
    'approveEmployer' : IDL.Func([UserId], [], []),
    'approveJob' : IDL.Func([JobId], [], []),
    'assignCallerUserRole' : IDL.Func([IDL.Principal, UserRole__1], [], []),
    'deactivateUser' : IDL.Func([UserId], [], []),
    'getCallerUserRole' : IDL.Func([], [UserRole__1], ['query']),
    'getEmployeeProfile' : IDL.Func(
        [UserId],
        [IDL.Opt(EmployeeProfile)],
        ['query'],
      ),
    'getEmployerProfile' : IDL.Func(
        [UserId],
        [IDL.Opt(EmployerProfile)],
        ['query'],
      ),
    'getJobApplications' : IDL.Func(
        [JobId],
        [IDL.Vec(JobApplication)],
        ['query'],
      ),
    'getJobDetails' : IDL.Func([JobId], [IDL.Opt(JobListing)], ['query']),
    'getMyApplications' : IDL.Func([], [IDL.Vec(JobApplication)], ['query']),
    'getMyEmployerJobs' : IDL.Func([], [IDL.Vec(JobListing)], ['query']),
    'getMyProfile' : IDL.Func([], [IDL.Opt(User)], ['query']),
    'getPlatformStats' : IDL.Func([], [PlatformStats], ['query']),
    'getSavedJobs' : IDL.Func([], [IDL.Vec(JobListing)], ['query']),
    'getUserList' : IDL.Func([], [IDL.Vec(User)], ['query']),
    'isCallerAdmin' : IDL.Func([], [IDL.Bool], ['query']),
    'postJob' : IDL.Func(
        [
          IDL.Text,
          IDL.Text,
          IDL.Text,
          IDL.Nat,
          IDL.Nat,
          IDL.Nat,
          JobType,
          IDL.Vec(IDL.Text),
          Timestamp,
        ],
        [JobId],
        [],
      ),
    'reactivateUser' : IDL.Func([UserId], [], []),
    'registerUser' : IDL.Func([UserRole, IDL.Text, IDL.Text], [], []),
    'rejectJob' : IDL.Func([JobId], [], []),
    'saveJob' : IDL.Func([JobId], [], []),
    'searchJobs' : IDL.Func(
        [JobSearchFilter],
        [IDL.Vec(JobListing)],
        ['query'],
      ),
    'suspendEmployer' : IDL.Func([UserId], [], []),
    'unsaveJob' : IDL.Func([JobId], [], []),
    'updateApplicationStatus' : IDL.Func(
        [ApplicationId, ApplicationStatus, IDL.Opt(IDL.Text)],
        [],
        [],
      ),
    'updateEmployeeProfile' : IDL.Func(
        [
          IDL.Text,
          IDL.Text,
          IDL.Vec(IDL.Text),
          IDL.Text,
          IDL.Vec(ExperienceEntry),
          IDL.Opt(ExternalBlob),
        ],
        [],
        [],
      ),
    'updateEmployerProfile' : IDL.Func(
        [IDL.Text, IDL.Text, IDL.Text, IDL.Text, IDL.Text],
        [],
        [],
      ),
    'updateJob' : IDL.Func(
        [
          JobId,
          IDL.Text,
          IDL.Text,
          IDL.Text,
          IDL.Nat,
          IDL.Nat,
          IDL.Nat,
          JobType,
          IDL.Vec(IDL.Text),
          JobStatus,
          Timestamp,
        ],
        [],
        [],
      ),
  });
};

export const init = ({ IDL }) => { return []; };