/* eslint-disable */

// @ts-nocheck

// This file was automatically generated by @caffeinelabs/bindgen@0.1.0.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Actor, HttpAgent, type HttpAgentOptions, type ActorConfig, type Agent, type ActorSubclass } from "@icp-sdk/core/agent";
import type { Principal } from "@icp-sdk/core/principal";
import { idlFactory, type _SERVICE } from "./declarations/backend.did";
export interface Some<T> {
    __kind__: "Some";
    value: T;
}
export interface None {
    __kind__: "None";
}
export type Option<T> = Some<T> | None;
function some<T>(value: T): Some<T> {
    return {
        __kind__: "Some",
        value: value
    };
}
function none(): None {
    return {
        __kind__: "None"
    };
}
function isNone<T>(option: Option<T>): option is None {
    return option.__kind__ === "None";
}
function isSome<T>(option: Option<T>): option is Some<T> {
    return option.__kind__ === "Some";
}
function unwrap<T>(option: Option<T>): T {
    if (isNone(option)) {
        throw new Error("unwrap: none");
    }
    return option.value;
}
function candid_some<T>(value: T): [T] {
    return [
        value
    ];
}
function candid_none<T>(): [] {
    return [];
}
function record_opt_to_undefined<T>(arg: T | null): T | undefined {
    return arg == null ? undefined : arg;
}
export class ExternalBlob {
    _blob?: Uint8Array<ArrayBuffer> | null;
    directURL: string;
    onProgress?: (percentage: number) => void = undefined;
    private constructor(directURL: string, blob: Uint8Array<ArrayBuffer> | null){
        if (blob) {
            this._blob = blob;
        }
        this.directURL = directURL;
    }
    static fromURL(url: string): ExternalBlob {
        return new ExternalBlob(url, null);
    }
    static fromBytes(blob: Uint8Array<ArrayBuffer>): ExternalBlob {
        const url = URL.createObjectURL(new Blob([
            new Uint8Array(blob)
        ], {
            type: 'application/octet-stream'
        }));
        return new ExternalBlob(url, blob);
    }
    public async getBytes(): Promise<Uint8Array<ArrayBuffer>> {
        if (this._blob) {
            return this._blob;
        }
        const response = await fetch(this.directURL);
        const blob = await response.blob();
        this._blob = new Uint8Array(await blob.arrayBuffer());
        return this._blob;
    }
    public getDirectURL(): string {
        return this.directURL;
    }
    public withUploadProgress(onProgress: (percentage: number) => void): ExternalBlob {
        this.onProgress = onProgress;
        return this;
    }
}
export interface EmployerProfile {
    status: EmployerStatus;
    userId: UserId;
    description: string;
    companyEmail: string;
    companyName: string;
    companySize: string;
    industry: string;
}
export type Timestamp = bigint;
export type ApplicationId = bigint;
export interface JobSearchFilter {
    jobType?: JobType;
    salaryMax?: bigint;
    salaryMin?: bigint;
    keyword?: string;
    location?: string;
}
export interface User {
    status: UserStatus;
    principal: UserId;
    name: string;
    createdAt: Timestamp;
    role: UserRole;
    email: string;
}
export interface _ImmutableObjectStorageRefillInformation {
    proposed_top_up_amount?: bigint;
}
export type JobId = bigint;
export interface _ImmutableObjectStorageCreateCertificateResult {
    method: string;
    blob_hash: string;
}
export interface JobListing {
    applicationDeadline: Timestamp;
    status: JobStatus;
    title: string;
    jobType: JobType;
    createdAt: Timestamp;
    experienceRequired: bigint;
    jobId: JobId;
    skillsRequired: Array<string>;
    description: string;
    updatedAt: Timestamp;
    employerId: UserId;
    salaryMax: bigint;
    salaryMin: bigint;
    location: string;
}
export interface JobApplication {
    status: ApplicationStatus;
    appliedAt: Timestamp;
    applicationId: ApplicationId;
    jobId: JobId;
    updatedAt: Timestamp;
    employeeId: UserId;
    notes?: string;
}
export interface ExperienceEntry {
    title: string;
    endDate?: string;
    description: string;
    company: string;
    startDate: string;
}
export interface _ImmutableObjectStorageRefillResult {
    success?: boolean;
    topped_up_amount?: bigint;
}
export type UserId = Principal;
export interface EmployeeProfile {
    userId: UserId;
    resumeFileId?: ExternalBlob;
    experience: Array<ExperienceEntry>;
    phone: string;
    skills: Array<string>;
    location: string;
    professionalSummary: string;
}
export interface PlatformStats {
    totalEmployees: bigint;
    totalEmployers: bigint;
    totalJobs: bigint;
    totalUsers: bigint;
    activeJobs: bigint;
    totalApplications: bigint;
}
export enum ApplicationStatus {
    offer = "offer",
    interview = "interview",
    applied = "applied",
    rejected = "rejected",
    shortlisted = "shortlisted"
}
export enum EmployerStatus {
    pending = "pending",
    approved = "approved",
    suspended = "suspended"
}
export enum JobStatus {
    closed = "closed",
    active = "active",
    draft = "draft"
}
export enum JobType {
    contract = "contract",
    partTime = "partTime",
    fullTime = "fullTime"
}
export enum UserRole {
    admin = "admin",
    employee = "employee",
    employer = "employer"
}
export enum UserRole__1 {
    admin = "admin",
    user = "user",
    guest = "guest"
}
export enum UserStatus {
    active = "active",
    inactive = "inactive"
}
export interface backendInterface {
    _immutableObjectStorageBlobsAreLive(hashes: Array<Uint8Array>): Promise<Array<boolean>>;
    _immutableObjectStorageBlobsToDelete(): Promise<Array<Uint8Array>>;
    _immutableObjectStorageConfirmBlobDeletion(blobs: Array<Uint8Array>): Promise<void>;
    _immutableObjectStorageCreateCertificate(blobHash: string): Promise<_ImmutableObjectStorageCreateCertificateResult>;
    _immutableObjectStorageRefillCashier(refillInformation: _ImmutableObjectStorageRefillInformation | null): Promise<_ImmutableObjectStorageRefillResult>;
    _immutableObjectStorageUpdateGatewayPrincipals(): Promise<void>;
    _initializeAccessControl(): Promise<void>;
    applyToJob(jobId: JobId): Promise<ApplicationId>;
    approveEmployer(userId: UserId): Promise<void>;
    approveJob(jobId: JobId): Promise<void>;
    assignCallerUserRole(user: Principal, role: UserRole__1): Promise<void>;
    deactivateUser(userId: UserId): Promise<void>;
    getCallerUserRole(): Promise<UserRole__1>;
    getEmployeeProfile(userId: UserId): Promise<EmployeeProfile | null>;
    getEmployerProfile(userId: UserId): Promise<EmployerProfile | null>;
    getJobApplications(jobId: JobId): Promise<Array<JobApplication>>;
    getJobDetails(jobId: JobId): Promise<JobListing | null>;
    getMyApplications(): Promise<Array<JobApplication>>;
    getMyEmployerJobs(): Promise<Array<JobListing>>;
    getMyProfile(): Promise<User | null>;
    getPlatformStats(): Promise<PlatformStats>;
    getSavedJobs(): Promise<Array<JobListing>>;
    getUserList(): Promise<Array<User>>;
    isCallerAdmin(): Promise<boolean>;
    postJob(title: string, description: string, location: string, salaryMin: bigint, salaryMax: bigint, experienceRequired: bigint, jobType: JobType, skillsRequired: Array<string>, applicationDeadline: Timestamp): Promise<JobId>;
    reactivateUser(userId: UserId): Promise<void>;
    registerUser(role: UserRole, name: string, email: string): Promise<void>;
    rejectJob(jobId: JobId): Promise<void>;
    saveJob(jobId: JobId): Promise<void>;
    searchJobs(filter: JobSearchFilter): Promise<Array<JobListing>>;
    suspendEmployer(userId: UserId): Promise<void>;
    unsaveJob(jobId: JobId): Promise<void>;
    updateApplicationStatus(applicationId: ApplicationId, status: ApplicationStatus, notes: string | null): Promise<void>;
    updateEmployeeProfile(location: string, phone: string, skills: Array<string>, professionalSummary: string, experience: Array<ExperienceEntry>, resumeFileId: ExternalBlob | null): Promise<void>;
    updateEmployerProfile(companyName: string, companyEmail: string, companySize: string, industry: string, description: string): Promise<void>;
    updateJob(jobId: JobId, title: string, description: string, location: string, salaryMin: bigint, salaryMax: bigint, experienceRequired: bigint, jobType: JobType, skillsRequired: Array<string>, status: JobStatus, applicationDeadline: Timestamp): Promise<void>;
}
import type { ApplicationId as _ApplicationId, ApplicationStatus as _ApplicationStatus, EmployeeProfile as _EmployeeProfile, EmployerProfile as _EmployerProfile, EmployerStatus as _EmployerStatus, ExperienceEntry as _ExperienceEntry, ExternalBlob as _ExternalBlob, JobApplication as _JobApplication, JobId as _JobId, JobListing as _JobListing, JobSearchFilter as _JobSearchFilter, JobStatus as _JobStatus, JobType as _JobType, Timestamp as _Timestamp, User as _User, UserId as _UserId, UserRole as _UserRole, UserRole__1 as _UserRole__1, UserStatus as _UserStatus, _ImmutableObjectStorageRefillInformation as __ImmutableObjectStorageRefillInformation, _ImmutableObjectStorageRefillResult as __ImmutableObjectStorageRefillResult } from "./declarations/backend.did.d.ts";
export class Backend implements backendInterface {
    constructor(private actor: ActorSubclass<_SERVICE>, private _uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, private _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, private processError?: (error: unknown) => never){}
    async _immutableObjectStorageBlobsAreLive(arg0: Array<Uint8Array>): Promise<Array<boolean>> {
        if (this.processError) {
            try {
                const result = await this.actor._immutableObjectStorageBlobsAreLive(arg0);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor._immutableObjectStorageBlobsAreLive(arg0);
            return result;
        }
    }
    async _immutableObjectStorageBlobsToDelete(): Promise<Array<Uint8Array>> {
        if (this.processError) {
            try {
                const result = await this.actor._immutableObjectStorageBlobsToDelete();
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor._immutableObjectStorageBlobsToDelete();
            return result;
        }
    }
    async _immutableObjectStorageConfirmBlobDeletion(arg0: Array<Uint8Array>): Promise<void> {
        if (this.processError) {
            try {
                const result = await this.actor._immutableObjectStorageConfirmBlobDeletion(arg0);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor._immutableObjectStorageConfirmBlobDeletion(arg0);
            return result;
        }
    }
    async _immutableObjectStorageCreateCertificate(arg0: string): Promise<_ImmutableObjectStorageCreateCertificateResult> {
        if (this.processError) {
            try {
                const result = await this.actor._immutableObjectStorageCreateCertificate(arg0);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor._immutableObjectStorageCreateCertificate(arg0);
            return result;
        }
    }
    async _immutableObjectStorageRefillCashier(arg0: _ImmutableObjectStorageRefillInformation | null): Promise<_ImmutableObjectStorageRefillResult> {
        if (this.processError) {
            try {
                const result = await this.actor._immutableObjectStorageRefillCashier(to_candid_opt_n1(this._uploadFile, this._downloadFile, arg0));
                return from_candid__ImmutableObjectStorageRefillResult_n4(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor._immutableObjectStorageRefillCashier(to_candid_opt_n1(this._uploadFile, this._downloadFile, arg0));
            return from_candid__ImmutableObjectStorageRefillResult_n4(this._uploadFile, this._downloadFile, result);
        }
    }
    async _immutableObjectStorageUpdateGatewayPrincipals(): Promise<void> {
        if (this.processError) {
            try {
                const result = await this.actor._immutableObjectStorageUpdateGatewayPrincipals();
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor._immutableObjectStorageUpdateGatewayPrincipals();
            return result;
        }
    }
    async _initializeAccessControl(): Promise<void> {
        if (this.processError) {
            try {
                const result = await this.actor._initializeAccessControl();
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor._initializeAccessControl();
            return result;
        }
    }
    async applyToJob(arg0: JobId): Promise<ApplicationId> {
        if (this.processError) {
            try {
                const result = await this.actor.applyToJob(arg0);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.applyToJob(arg0);
            return result;
        }
    }
    async approveEmployer(arg0: UserId): Promise<void> {
        if (this.processError) {
            try {
                const result = await this.actor.approveEmployer(arg0);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.approveEmployer(arg0);
            return result;
        }
    }
    async approveJob(arg0: JobId): Promise<void> {
        if (this.processError) {
            try {
                const result = await this.actor.approveJob(arg0);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.approveJob(arg0);
            return result;
        }
    }
    async assignCallerUserRole(arg0: Principal, arg1: UserRole__1): Promise<void> {
        if (this.processError) {
            try {
                const result = await this.actor.assignCallerUserRole(arg0, to_candid_UserRole__1_n8(this._uploadFile, this._downloadFile, arg1));
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.assignCallerUserRole(arg0, to_candid_UserRole__1_n8(this._uploadFile, this._downloadFile, arg1));
            return result;
        }
    }
    async deactivateUser(arg0: UserId): Promise<void> {
        if (this.processError) {
            try {
                const result = await this.actor.deactivateUser(arg0);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.deactivateUser(arg0);
            return result;
        }
    }
    async getCallerUserRole(): Promise<UserRole__1> {
        if (this.processError) {
            try {
                const result = await this.actor.getCallerUserRole();
                return from_candid_UserRole__1_n10(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getCallerUserRole();
            return from_candid_UserRole__1_n10(this._uploadFile, this._downloadFile, result);
        }
    }
    async getEmployeeProfile(arg0: UserId): Promise<EmployeeProfile | null> {
        if (this.processError) {
            try {
                const result = await this.actor.getEmployeeProfile(arg0);
                return from_candid_opt_n12(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getEmployeeProfile(arg0);
            return from_candid_opt_n12(this._uploadFile, this._downloadFile, result);
        }
    }
    async getEmployerProfile(arg0: UserId): Promise<EmployerProfile | null> {
        if (this.processError) {
            try {
                const result = await this.actor.getEmployerProfile(arg0);
                return from_candid_opt_n21(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getEmployerProfile(arg0);
            return from_candid_opt_n21(this._uploadFile, this._downloadFile, result);
        }
    }
    async getJobApplications(arg0: JobId): Promise<Array<JobApplication>> {
        if (this.processError) {
            try {
                const result = await this.actor.getJobApplications(arg0);
                return from_candid_vec_n26(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getJobApplications(arg0);
            return from_candid_vec_n26(this._uploadFile, this._downloadFile, result);
        }
    }
    async getJobDetails(arg0: JobId): Promise<JobListing | null> {
        if (this.processError) {
            try {
                const result = await this.actor.getJobDetails(arg0);
                return from_candid_opt_n31(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getJobDetails(arg0);
            return from_candid_opt_n31(this._uploadFile, this._downloadFile, result);
        }
    }
    async getMyApplications(): Promise<Array<JobApplication>> {
        if (this.processError) {
            try {
                const result = await this.actor.getMyApplications();
                return from_candid_vec_n26(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getMyApplications();
            return from_candid_vec_n26(this._uploadFile, this._downloadFile, result);
        }
    }
    async getMyEmployerJobs(): Promise<Array<JobListing>> {
        if (this.processError) {
            try {
                const result = await this.actor.getMyEmployerJobs();
                return from_candid_vec_n38(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getMyEmployerJobs();
            return from_candid_vec_n38(this._uploadFile, this._downloadFile, result);
        }
    }
    async getMyProfile(): Promise<User | null> {
        if (this.processError) {
            try {
                const result = await this.actor.getMyProfile();
                return from_candid_opt_n39(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getMyProfile();
            return from_candid_opt_n39(this._uploadFile, this._downloadFile, result);
        }
    }
    async getPlatformStats(): Promise<PlatformStats> {
        if (this.processError) {
            try {
                const result = await this.actor.getPlatformStats();
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getPlatformStats();
            return result;
        }
    }
    async getSavedJobs(): Promise<Array<JobListing>> {
        if (this.processError) {
            try {
                const result = await this.actor.getSavedJobs();
                return from_candid_vec_n38(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getSavedJobs();
            return from_candid_vec_n38(this._uploadFile, this._downloadFile, result);
        }
    }
    async getUserList(): Promise<Array<User>> {
        if (this.processError) {
            try {
                const result = await this.actor.getUserList();
                return from_candid_vec_n46(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getUserList();
            return from_candid_vec_n46(this._uploadFile, this._downloadFile, result);
        }
    }
    async isCallerAdmin(): Promise<boolean> {
        if (this.processError) {
            try {
                const result = await this.actor.isCallerAdmin();
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.isCallerAdmin();
            return result;
        }
    }
    async postJob(arg0: string, arg1: string, arg2: string, arg3: bigint, arg4: bigint, arg5: bigint, arg6: JobType, arg7: Array<string>, arg8: Timestamp): Promise<JobId> {
        if (this.processError) {
            try {
                const result = await this.actor.postJob(arg0, arg1, arg2, arg3, arg4, arg5, to_candid_JobType_n47(this._uploadFile, this._downloadFile, arg6), arg7, arg8);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.postJob(arg0, arg1, arg2, arg3, arg4, arg5, to_candid_JobType_n47(this._uploadFile, this._downloadFile, arg6), arg7, arg8);
            return result;
        }
    }
    async reactivateUser(arg0: UserId): Promise<void> {
        if (this.processError) {
            try {
                const result = await this.actor.reactivateUser(arg0);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.reactivateUser(arg0);
            return result;
        }
    }
    async registerUser(arg0: UserRole, arg1: string, arg2: string): Promise<void> {
        if (this.processError) {
            try {
                const result = await this.actor.registerUser(to_candid_UserRole_n49(this._uploadFile, this._downloadFile, arg0), arg1, arg2);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.registerUser(to_candid_UserRole_n49(this._uploadFile, this._downloadFile, arg0), arg1, arg2);
            return result;
        }
    }
    async rejectJob(arg0: JobId): Promise<void> {
        if (this.processError) {
            try {
                const result = await this.actor.rejectJob(arg0);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.rejectJob(arg0);
            return result;
        }
    }
    async saveJob(arg0: JobId): Promise<void> {
        if (this.processError) {
            try {
                const result = await this.actor.saveJob(arg0);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.saveJob(arg0);
            return result;
        }
    }
    async searchJobs(arg0: JobSearchFilter): Promise<Array<JobListing>> {
        if (this.processError) {
            try {
                const result = await this.actor.searchJobs(to_candid_JobSearchFilter_n51(this._uploadFile, this._downloadFile, arg0));
                return from_candid_vec_n38(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.searchJobs(to_candid_JobSearchFilter_n51(this._uploadFile, this._downloadFile, arg0));
            return from_candid_vec_n38(this._uploadFile, this._downloadFile, result);
        }
    }
    async suspendEmployer(arg0: UserId): Promise<void> {
        if (this.processError) {
            try {
                const result = await this.actor.suspendEmployer(arg0);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.suspendEmployer(arg0);
            return result;
        }
    }
    async unsaveJob(arg0: JobId): Promise<void> {
        if (this.processError) {
            try {
                const result = await this.actor.unsaveJob(arg0);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.unsaveJob(arg0);
            return result;
        }
    }
    async updateApplicationStatus(arg0: ApplicationId, arg1: ApplicationStatus, arg2: string | null): Promise<void> {
        if (this.processError) {
            try {
                const result = await this.actor.updateApplicationStatus(arg0, to_candid_ApplicationStatus_n53(this._uploadFile, this._downloadFile, arg1), to_candid_opt_n55(this._uploadFile, this._downloadFile, arg2));
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.updateApplicationStatus(arg0, to_candid_ApplicationStatus_n53(this._uploadFile, this._downloadFile, arg1), to_candid_opt_n55(this._uploadFile, this._downloadFile, arg2));
            return result;
        }
    }
    async updateEmployeeProfile(arg0: string, arg1: string, arg2: Array<string>, arg3: string, arg4: Array<ExperienceEntry>, arg5: ExternalBlob | null): Promise<void> {
        if (this.processError) {
            try {
                const result = await this.actor.updateEmployeeProfile(arg0, arg1, arg2, arg3, to_candid_vec_n56(this._uploadFile, this._downloadFile, arg4), await to_candid_opt_n59(this._uploadFile, this._downloadFile, arg5));
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.updateEmployeeProfile(arg0, arg1, arg2, arg3, to_candid_vec_n56(this._uploadFile, this._downloadFile, arg4), await to_candid_opt_n59(this._uploadFile, this._downloadFile, arg5));
            return result;
        }
    }
    async updateEmployerProfile(arg0: string, arg1: string, arg2: string, arg3: string, arg4: string): Promise<void> {
        if (this.processError) {
            try {
                const result = await this.actor.updateEmployerProfile(arg0, arg1, arg2, arg3, arg4);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.updateEmployerProfile(arg0, arg1, arg2, arg3, arg4);
            return result;
        }
    }
    async updateJob(arg0: JobId, arg1: string, arg2: string, arg3: string, arg4: bigint, arg5: bigint, arg6: bigint, arg7: JobType, arg8: Array<string>, arg9: JobStatus, arg10: Timestamp): Promise<void> {
        if (this.processError) {
            try {
                const result = await this.actor.updateJob(arg0, arg1, arg2, arg3, arg4, arg5, arg6, to_candid_JobType_n47(this._uploadFile, this._downloadFile, arg7), arg8, to_candid_JobStatus_n61(this._uploadFile, this._downloadFile, arg9), arg10);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.updateJob(arg0, arg1, arg2, arg3, arg4, arg5, arg6, to_candid_JobType_n47(this._uploadFile, this._downloadFile, arg7), arg8, to_candid_JobStatus_n61(this._uploadFile, this._downloadFile, arg9), arg10);
            return result;
        }
    }
}
function from_candid_ApplicationStatus_n29(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: _ApplicationStatus): ApplicationStatus {
    return from_candid_variant_n30(_uploadFile, _downloadFile, value);
}
async function from_candid_EmployeeProfile_n13(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: _EmployeeProfile): Promise<EmployeeProfile> {
    return await from_candid_record_n14(_uploadFile, _downloadFile, value);
}
function from_candid_EmployerProfile_n22(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: _EmployerProfile): EmployerProfile {
    return from_candid_record_n23(_uploadFile, _downloadFile, value);
}
function from_candid_EmployerStatus_n24(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: _EmployerStatus): EmployerStatus {
    return from_candid_variant_n25(_uploadFile, _downloadFile, value);
}
function from_candid_ExperienceEntry_n18(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: _ExperienceEntry): ExperienceEntry {
    return from_candid_record_n19(_uploadFile, _downloadFile, value);
}
async function from_candid_ExternalBlob_n16(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: _ExternalBlob): Promise<ExternalBlob> {
    return await _downloadFile(value);
}
function from_candid_JobApplication_n27(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: _JobApplication): JobApplication {
    return from_candid_record_n28(_uploadFile, _downloadFile, value);
}
function from_candid_JobListing_n32(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: _JobListing): JobListing {
    return from_candid_record_n33(_uploadFile, _downloadFile, value);
}
function from_candid_JobStatus_n34(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: _JobStatus): JobStatus {
    return from_candid_variant_n35(_uploadFile, _downloadFile, value);
}
function from_candid_JobType_n36(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: _JobType): JobType {
    return from_candid_variant_n37(_uploadFile, _downloadFile, value);
}
function from_candid_UserRole__1_n10(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: _UserRole__1): UserRole__1 {
    return from_candid_variant_n11(_uploadFile, _downloadFile, value);
}
function from_candid_UserRole_n44(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: _UserRole): UserRole {
    return from_candid_variant_n45(_uploadFile, _downloadFile, value);
}
function from_candid_UserStatus_n42(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: _UserStatus): UserStatus {
    return from_candid_variant_n43(_uploadFile, _downloadFile, value);
}
function from_candid_User_n40(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: _User): User {
    return from_candid_record_n41(_uploadFile, _downloadFile, value);
}
function from_candid__ImmutableObjectStorageRefillResult_n4(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: __ImmutableObjectStorageRefillResult): _ImmutableObjectStorageRefillResult {
    return from_candid_record_n5(_uploadFile, _downloadFile, value);
}
async function from_candid_opt_n12(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: [] | [_EmployeeProfile]): Promise<EmployeeProfile | null> {
    return value.length === 0 ? null : await from_candid_EmployeeProfile_n13(_uploadFile, _downloadFile, value[0]);
}
async function from_candid_opt_n15(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: [] | [_ExternalBlob]): Promise<ExternalBlob | null> {
    return value.length === 0 ? null : await from_candid_ExternalBlob_n16(_uploadFile, _downloadFile, value[0]);
}
function from_candid_opt_n20(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: [] | [string]): string | null {
    return value.length === 0 ? null : value[0];
}
function from_candid_opt_n21(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: [] | [_EmployerProfile]): EmployerProfile | null {
    return value.length === 0 ? null : from_candid_EmployerProfile_n22(_uploadFile, _downloadFile, value[0]);
}
function from_candid_opt_n31(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: [] | [_JobListing]): JobListing | null {
    return value.length === 0 ? null : from_candid_JobListing_n32(_uploadFile, _downloadFile, value[0]);
}
function from_candid_opt_n39(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: [] | [_User]): User | null {
    return value.length === 0 ? null : from_candid_User_n40(_uploadFile, _downloadFile, value[0]);
}
function from_candid_opt_n6(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: [] | [boolean]): boolean | null {
    return value.length === 0 ? null : value[0];
}
function from_candid_opt_n7(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: [] | [bigint]): bigint | null {
    return value.length === 0 ? null : value[0];
}
async function from_candid_record_n14(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    userId: _UserId;
    resumeFileId: [] | [_ExternalBlob];
    experience: Array<_ExperienceEntry>;
    phone: string;
    skills: Array<string>;
    location: string;
    professionalSummary: string;
}): Promise<{
    userId: UserId;
    resumeFileId?: ExternalBlob;
    experience: Array<ExperienceEntry>;
    phone: string;
    skills: Array<string>;
    location: string;
    professionalSummary: string;
}> {
    return {
        userId: value.userId,
        resumeFileId: record_opt_to_undefined(await from_candid_opt_n15(_uploadFile, _downloadFile, value.resumeFileId)),
        experience: from_candid_vec_n17(_uploadFile, _downloadFile, value.experience),
        phone: value.phone,
        skills: value.skills,
        location: value.location,
        professionalSummary: value.professionalSummary
    };
}
function from_candid_record_n19(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    title: string;
    endDate: [] | [string];
    description: string;
    company: string;
    startDate: string;
}): {
    title: string;
    endDate?: string;
    description: string;
    company: string;
    startDate: string;
} {
    return {
        title: value.title,
        endDate: record_opt_to_undefined(from_candid_opt_n20(_uploadFile, _downloadFile, value.endDate)),
        description: value.description,
        company: value.company,
        startDate: value.startDate
    };
}
function from_candid_record_n23(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    status: _EmployerStatus;
    userId: _UserId;
    description: string;
    companyEmail: string;
    companyName: string;
    companySize: string;
    industry: string;
}): {
    status: EmployerStatus;
    userId: UserId;
    description: string;
    companyEmail: string;
    companyName: string;
    companySize: string;
    industry: string;
} {
    return {
        status: from_candid_EmployerStatus_n24(_uploadFile, _downloadFile, value.status),
        userId: value.userId,
        description: value.description,
        companyEmail: value.companyEmail,
        companyName: value.companyName,
        companySize: value.companySize,
        industry: value.industry
    };
}
function from_candid_record_n28(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    status: _ApplicationStatus;
    appliedAt: _Timestamp;
    applicationId: _ApplicationId;
    jobId: _JobId;
    updatedAt: _Timestamp;
    employeeId: _UserId;
    notes: [] | [string];
}): {
    status: ApplicationStatus;
    appliedAt: Timestamp;
    applicationId: ApplicationId;
    jobId: JobId;
    updatedAt: Timestamp;
    employeeId: UserId;
    notes?: string;
} {
    return {
        status: from_candid_ApplicationStatus_n29(_uploadFile, _downloadFile, value.status),
        appliedAt: value.appliedAt,
        applicationId: value.applicationId,
        jobId: value.jobId,
        updatedAt: value.updatedAt,
        employeeId: value.employeeId,
        notes: record_opt_to_undefined(from_candid_opt_n20(_uploadFile, _downloadFile, value.notes))
    };
}
function from_candid_record_n33(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    applicationDeadline: _Timestamp;
    status: _JobStatus;
    title: string;
    jobType: _JobType;
    createdAt: _Timestamp;
    experienceRequired: bigint;
    jobId: _JobId;
    skillsRequired: Array<string>;
    description: string;
    updatedAt: _Timestamp;
    employerId: _UserId;
    salaryMax: bigint;
    salaryMin: bigint;
    location: string;
}): {
    applicationDeadline: Timestamp;
    status: JobStatus;
    title: string;
    jobType: JobType;
    createdAt: Timestamp;
    experienceRequired: bigint;
    jobId: JobId;
    skillsRequired: Array<string>;
    description: string;
    updatedAt: Timestamp;
    employerId: UserId;
    salaryMax: bigint;
    salaryMin: bigint;
    location: string;
} {
    return {
        applicationDeadline: value.applicationDeadline,
        status: from_candid_JobStatus_n34(_uploadFile, _downloadFile, value.status),
        title: value.title,
        jobType: from_candid_JobType_n36(_uploadFile, _downloadFile, value.jobType),
        createdAt: value.createdAt,
        experienceRequired: value.experienceRequired,
        jobId: value.jobId,
        skillsRequired: value.skillsRequired,
        description: value.description,
        updatedAt: value.updatedAt,
        employerId: value.employerId,
        salaryMax: value.salaryMax,
        salaryMin: value.salaryMin,
        location: value.location
    };
}
function from_candid_record_n41(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    status: _UserStatus;
    principal: _UserId;
    name: string;
    createdAt: _Timestamp;
    role: _UserRole;
    email: string;
}): {
    status: UserStatus;
    principal: UserId;
    name: string;
    createdAt: Timestamp;
    role: UserRole;
    email: string;
} {
    return {
        status: from_candid_UserStatus_n42(_uploadFile, _downloadFile, value.status),
        principal: value.principal,
        name: value.name,
        createdAt: value.createdAt,
        role: from_candid_UserRole_n44(_uploadFile, _downloadFile, value.role),
        email: value.email
    };
}
function from_candid_record_n5(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    success: [] | [boolean];
    topped_up_amount: [] | [bigint];
}): {
    success?: boolean;
    topped_up_amount?: bigint;
} {
    return {
        success: record_opt_to_undefined(from_candid_opt_n6(_uploadFile, _downloadFile, value.success)),
        topped_up_amount: record_opt_to_undefined(from_candid_opt_n7(_uploadFile, _downloadFile, value.topped_up_amount))
    };
}
function from_candid_variant_n11(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    admin: null;
} | {
    user: null;
} | {
    guest: null;
}): UserRole__1 {
    return "admin" in value ? UserRole__1.admin : "user" in value ? UserRole__1.user : "guest" in value ? UserRole__1.guest : value;
}
function from_candid_variant_n25(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    pending: null;
} | {
    approved: null;
} | {
    suspended: null;
}): EmployerStatus {
    return "pending" in value ? EmployerStatus.pending : "approved" in value ? EmployerStatus.approved : "suspended" in value ? EmployerStatus.suspended : value;
}
function from_candid_variant_n30(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    offer: null;
} | {
    interview: null;
} | {
    applied: null;
} | {
    rejected: null;
} | {
    shortlisted: null;
}): ApplicationStatus {
    return "offer" in value ? ApplicationStatus.offer : "interview" in value ? ApplicationStatus.interview : "applied" in value ? ApplicationStatus.applied : "rejected" in value ? ApplicationStatus.rejected : "shortlisted" in value ? ApplicationStatus.shortlisted : value;
}
function from_candid_variant_n35(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    closed: null;
} | {
    active: null;
} | {
    draft: null;
}): JobStatus {
    return "closed" in value ? JobStatus.closed : "active" in value ? JobStatus.active : "draft" in value ? JobStatus.draft : value;
}
function from_candid_variant_n37(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    contract: null;
} | {
    partTime: null;
} | {
    fullTime: null;
}): JobType {
    return "contract" in value ? JobType.contract : "partTime" in value ? JobType.partTime : "fullTime" in value ? JobType.fullTime : value;
}
function from_candid_variant_n43(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    active: null;
} | {
    inactive: null;
}): UserStatus {
    return "active" in value ? UserStatus.active : "inactive" in value ? UserStatus.inactive : value;
}
function from_candid_variant_n45(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    admin: null;
} | {
    employee: null;
} | {
    employer: null;
}): UserRole {
    return "admin" in value ? UserRole.admin : "employee" in value ? UserRole.employee : "employer" in value ? UserRole.employer : value;
}
function from_candid_vec_n17(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: Array<_ExperienceEntry>): Array<ExperienceEntry> {
    return value.map((x)=>from_candid_ExperienceEntry_n18(_uploadFile, _downloadFile, x));
}
function from_candid_vec_n26(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: Array<_JobApplication>): Array<JobApplication> {
    return value.map((x)=>from_candid_JobApplication_n27(_uploadFile, _downloadFile, x));
}
function from_candid_vec_n38(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: Array<_JobListing>): Array<JobListing> {
    return value.map((x)=>from_candid_JobListing_n32(_uploadFile, _downloadFile, x));
}
function from_candid_vec_n46(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: Array<_User>): Array<User> {
    return value.map((x)=>from_candid_User_n40(_uploadFile, _downloadFile, x));
}
function to_candid_ApplicationStatus_n53(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: ApplicationStatus): _ApplicationStatus {
    return to_candid_variant_n54(_uploadFile, _downloadFile, value);
}
function to_candid_ExperienceEntry_n57(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: ExperienceEntry): _ExperienceEntry {
    return to_candid_record_n58(_uploadFile, _downloadFile, value);
}
async function to_candid_ExternalBlob_n60(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: ExternalBlob): Promise<_ExternalBlob> {
    return await _uploadFile(value);
}
function to_candid_JobSearchFilter_n51(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: JobSearchFilter): _JobSearchFilter {
    return to_candid_record_n52(_uploadFile, _downloadFile, value);
}
function to_candid_JobStatus_n61(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: JobStatus): _JobStatus {
    return to_candid_variant_n62(_uploadFile, _downloadFile, value);
}
function to_candid_JobType_n47(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: JobType): _JobType {
    return to_candid_variant_n48(_uploadFile, _downloadFile, value);
}
function to_candid_UserRole__1_n8(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: UserRole__1): _UserRole__1 {
    return to_candid_variant_n9(_uploadFile, _downloadFile, value);
}
function to_candid_UserRole_n49(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: UserRole): _UserRole {
    return to_candid_variant_n50(_uploadFile, _downloadFile, value);
}
function to_candid__ImmutableObjectStorageRefillInformation_n2(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: _ImmutableObjectStorageRefillInformation): __ImmutableObjectStorageRefillInformation {
    return to_candid_record_n3(_uploadFile, _downloadFile, value);
}
function to_candid_opt_n1(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: _ImmutableObjectStorageRefillInformation | null): [] | [__ImmutableObjectStorageRefillInformation] {
    return value === null ? candid_none() : candid_some(to_candid__ImmutableObjectStorageRefillInformation_n2(_uploadFile, _downloadFile, value));
}
function to_candid_opt_n55(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: string | null): [] | [string] {
    return value === null ? candid_none() : candid_some(value);
}
async function to_candid_opt_n59(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: ExternalBlob | null): Promise<[] | [_ExternalBlob]> {
    return value === null ? candid_none() : candid_some(await to_candid_ExternalBlob_n60(_uploadFile, _downloadFile, value));
}
function to_candid_record_n3(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    proposed_top_up_amount?: bigint;
}): {
    proposed_top_up_amount: [] | [bigint];
} {
    return {
        proposed_top_up_amount: value.proposed_top_up_amount ? candid_some(value.proposed_top_up_amount) : candid_none()
    };
}
function to_candid_record_n52(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    jobType?: JobType;
    salaryMax?: bigint;
    salaryMin?: bigint;
    keyword?: string;
    location?: string;
}): {
    jobType: [] | [_JobType];
    salaryMax: [] | [bigint];
    salaryMin: [] | [bigint];
    keyword: [] | [string];
    location: [] | [string];
} {
    return {
        jobType: value.jobType ? candid_some(to_candid_JobType_n47(_uploadFile, _downloadFile, value.jobType)) : candid_none(),
        salaryMax: value.salaryMax ? candid_some(value.salaryMax) : candid_none(),
        salaryMin: value.salaryMin ? candid_some(value.salaryMin) : candid_none(),
        keyword: value.keyword ? candid_some(value.keyword) : candid_none(),
        location: value.location ? candid_some(value.location) : candid_none()
    };
}
function to_candid_record_n58(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    title: string;
    endDate?: string;
    description: string;
    company: string;
    startDate: string;
}): {
    title: string;
    endDate: [] | [string];
    description: string;
    company: string;
    startDate: string;
} {
    return {
        title: value.title,
        endDate: value.endDate ? candid_some(value.endDate) : candid_none(),
        description: value.description,
        company: value.company,
        startDate: value.startDate
    };
}
function to_candid_variant_n48(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: JobType): {
    contract: null;
} | {
    partTime: null;
} | {
    fullTime: null;
} {
    return value == JobType.contract ? {
        contract: null
    } : value == JobType.partTime ? {
        partTime: null
    } : value == JobType.fullTime ? {
        fullTime: null
    } : value;
}
function to_candid_variant_n50(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: UserRole): {
    admin: null;
} | {
    employee: null;
} | {
    employer: null;
} {
    return value == UserRole.admin ? {
        admin: null
    } : value == UserRole.employee ? {
        employee: null
    } : value == UserRole.employer ? {
        employer: null
    } : value;
}
function to_candid_variant_n54(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: ApplicationStatus): {
    offer: null;
} | {
    interview: null;
} | {
    applied: null;
} | {
    rejected: null;
} | {
    shortlisted: null;
} {
    return value == ApplicationStatus.offer ? {
        offer: null
    } : value == ApplicationStatus.interview ? {
        interview: null
    } : value == ApplicationStatus.applied ? {
        applied: null
    } : value == ApplicationStatus.rejected ? {
        rejected: null
    } : value == ApplicationStatus.shortlisted ? {
        shortlisted: null
    } : value;
}
function to_candid_variant_n62(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: JobStatus): {
    closed: null;
} | {
    active: null;
} | {
    draft: null;
} {
    return value == JobStatus.closed ? {
        closed: null
    } : value == JobStatus.active ? {
        active: null
    } : value == JobStatus.draft ? {
        draft: null
    } : value;
}
function to_candid_variant_n9(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: UserRole__1): {
    admin: null;
} | {
    user: null;
} | {
    guest: null;
} {
    return value == UserRole__1.admin ? {
        admin: null
    } : value == UserRole__1.user ? {
        user: null
    } : value == UserRole__1.guest ? {
        guest: null
    } : value;
}
function to_candid_vec_n56(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: Array<ExperienceEntry>): Array<_ExperienceEntry> {
    return value.map((x)=>to_candid_ExperienceEntry_n57(_uploadFile, _downloadFile, x));
}
export interface CreateActorOptions {
    agent?: Agent;
    agentOptions?: HttpAgentOptions;
    actorOptions?: ActorConfig;
    processError?: (error: unknown) => never;
}
export function createActor(canisterId: string, _uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, options: CreateActorOptions = {}): Backend {
    const agent = options.agent || HttpAgent.createSync({
        ...options.agentOptions
    });
    if (options.agent && options.agentOptions) {
        console.warn("Detected both agent and agentOptions passed to createActor. Ignoring agentOptions and proceeding with the provided agent.");
    }
    const actor = Actor.createActor<_SERVICE>(idlFactory, {
        agent,
        canisterId: canisterId,
        ...options.actorOptions
    });
    return new Backend(actor, _uploadFile, _downloadFile, options.processError);
}
